<?php
$box = $this->box();

if (is_array($box)) : ?>
    <div class="checkout-types">
        LogisticPlus <strong>Total Box Volume </strong>
        <?php
        $totalQuantity = Mage::getModel('checkout/cart')->getQuote()->getItemsQty();
        echo '(' . $totalQuantity . ' * ' . $box['volume'] . ') : ';
        echo $total_volume = $box['volume'] * $totalQuantity . ' m3';
        ?>
    </div>
<?php endif; ?>